### ISSUE TITLE
Grafana admin permissions to users logged in via oauth2

### ISSUE THREAD

**Issue by saurabhpandit** [raspbernetes/k8s-gitops#110]
# Details

No user currently has admin permissions to Grafana. Users logged in via oauth2 should be made admins.

**Comment by xUnholy** [comment]
@carpenike you've managed to configure something similar for your cluster to provide admin to your instance correct?

**Comment by carpenike** [comment]
Yup! See https://github.com/carpenike/k8s-gitops/blob/master/cluster/monitoring/prometheus-operator/prometheus-operator-helm-values.txt#L40-L57.

I've got Dex running inside the cluster which basically centralizes all oauth requests rather than registering each client with GitHub. The key config is with the group mappings: https://github.com/carpenike/k8s-gitops/blob/master/cluster/monitoring/prometheus-operator/prometheus-operator-helm-values.txt#L55-L57. I've got a k8s-admins team in my GH organization that I map to the Admins group in Grafana.

**Comment by xUnholy** [comment]
Thanks @carpenike - Was `org_id: 1` required and is there some documentation in case of further group mappings?

Just pushed changes for this in the following commit https://github.com/raspbernetes/k8s-gitops/commit/bcc4d070bc9597c83e5fce6cfe656bd0ce7ded52

Once tested and verified will close this ticket.

**Comment by xUnholy** [comment]
Tested and worked 🎉
